# Generated by Django 3.2.6 on 2021-08-13 05:51

import autoslug.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('excerpt', models.TextField(verbose_name='Excerpt')),
                ('body', models.TextField(verbose_name='Body')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('published_on', models.DateTimeField(auto_now_add=True, verbose_name='Published On')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
