# Generated by Django 3.2.6 on 2021-08-14 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published_by',
            new_name='author',
        ),
    ]
