# Generated by Django 3.2.6 on 2021-08-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_published_by_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], max_length=10, verbose_name='User Type'),
        ),
    ]
