# Generated by Django 3.2.6 on 2021-08-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Published', max_length=10, verbose_name='User Type'),
        ),
    ]
